### PR TITLE
Updated deps to work with node 4

### PR DESCRIPTION
**Pull request by asbjornenge**
All test are passing. Tested on node v4.1.2.

### CODE REVIEW

**Comment by asbjornenge** [comment]
Makes sense for the CI to fail since it's using node v0.12.8.

**Comment by rjrodger** [comment]
+1!

**Comment by mrhooray** [comment]
this pr failed the travis run
i'll probably take some time to bring this to latest node
cc @asbjornenge @rjrodger

**Comment by asbjornenge** [comment]
Yeah, since we're already on 5.5 that probably makes sense :stuck_out_tongue: I'll just close this PR.

**Comment by mrhooray** [comment]
@asbjornenge @rjrodger 
passed node 4.2 and 5.5 on travis and released v0.2.0

**Pull request closed without merging**
